import {
  AlertCircle,
  Archive,
  ArrowLeft,
  BookCopy,
  Camera,
  Clock,
  Edit,
  Eye,
  FileJson,
  Fuel,
  Gauge,
  GripVertical,
  History,
  House,
  MinusCircle,
  PlusCircle,
  Power,
  PowerOff,
  RotateCcw,
  Save,
  Settings,
  Share2,
  Ship,
  Trash2,
  Warehouse,
  Wifi,
  WifiOff,
  X,
  Zap,
  AlertTriangle,
  LogOut,
} from 'lucide-react';
import { NewLogo } from './new-logo';

export const Icons = {
  alert: AlertCircle,
  archive: Archive,
  arrowLeft: ArrowLeft,
  book: BookCopy,
  camera: Camera,
  clock: Clock,
  edit: Edit,
  eye: Eye,
  file: FileJson,
  fuel: Fuel,
  gauge: Gauge,
  grip: GripVertical,
  history: History,
  home: House,
  minus: MinusCircle,
  plus: PlusCircle,
  power: Power,
  powerOff: PowerOff,
  reset: RotateCcw,
  save: Save,
  settings: Settings,
  share: Share2,
  ship: Ship,
  trash: Trash2,
  warehouse: Warehouse,
  wifi: Wifi,
  wifiOff: WifiOff,
  close: X,
  zap: Zap,
  logo: NewLogo,
  warning: AlertTriangle,
  logout: LogOut,
};
